# Total planning attempts
max_solutions: 10

# Planning group and link names
arm_group_name: "arm"
eef_name: "end_effector"
hand_group_name: "hand"
hand_frame: "link_art6"

# Poses
hand_open_pose: "opened"
hand_close_pose: "closed"
arm_home_pose: "vertical"

# Scene frames
world_frame: "dummy_link"
table_reference_frame: "dummy_link"
object_reference_frame: "dummy_link"
surface_link: "table"

# Collision object for picking
# CYLINDER object specifications
object_name: "object"
object_dimensions: [0.25, 0.02] # [height, radius]
object_pose: [0, -0.35, 0, 0, 0, 0]

# Table model
spawn_table: true
table_name: "table"
table_dimensions: [0.4, 1, 0.1]  # [length, width, height]
table_pose: [0, 0, 0, 0, 0, 0]

# Gripper grasp frame transform [x,y,z,r,p,y]
grasp_frame_transform: [0, 0, 0.17, 1.57, 0, 0]

# Place pose [x,y,z,r,p,y]
place_pose: [0, 0.45, 0, 0, 0, 0]
place_surface_offset: 0.0001 # place offset from table

# Valid distance range when approaching an object for picking
approach_object_min_dist: 0
approach_object_max_dist: 0.2

# Valid height range when lifting an object after pick
lift_object_min_dist: 0.01
lift_object_max_dist: 0.1