arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_base_art1_yaw
    - joint_art1_art2_pitch
    - joint_art2_art3_pitch
    - joint_art3_art4_roll
    - joint_art4_art5_pitch
    - joint_art5_art6_roll
  gains:
    joint_base_art1_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_art1_art2_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_art2_art3_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_art3_art4_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_art4_art5_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_art5_art6_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_hand_finger_left
  gains:
    joint_hand_finger_left:
      p: 1
      d: 0
      i: 0
      i_clamp: 1